version: '3.7'

networks:
  takeaway:
    external: true
    driver: "bridge"
    name: takeaway 

# volumes:

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    volumes:
      - ./project:/project
      - /project/.venv
    ports:
      - "9988:9988"
    networks:
      - takeaway