# Generated by Django 3.1 on 2020-12-05 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('company', '0002_auto_20201106_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.adminuser'),
        ),
    ]
