# Generated by Django 3.1 on 2020-12-07 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201206_1252'),
        ('company', '0003_company_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='company',
            name='postal_code',
            field=models.IntegerField(default=36600, verbose_name='postal code'),
        ),
        migrations.AlterField(
            model_name='company',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.adminuser', verbose_name='admin'),
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=120, verbose_name='name'),
        ),
    ]
