# Generated by Django 3.1 on 2020-12-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20201207_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='description'),
            preserve_default=False,
        ),
    ]
