# Generated by Django 3.1 on 2020-12-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=120)),
                ('phone_number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Base user',
                'verbose_name_plural': 'Base users',
                'db_table': 'baseuser',
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.baseuser',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.baseuser',),
        ),
    ]
