# Generated by Django 3.1 on 2020-12-06 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_baseuser_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='name',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date joined'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseuser',
            name='first_name',
            field=models.CharField(default='', max_length=60, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='last_name',
            field=models.CharField(default='', max_length=60, verbose_name='last name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='email',
            field=models.EmailField(max_length=120, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='password',
            field=models.CharField(max_length=50, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='phone_number',
            field=models.CharField(max_length=6, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='User', max_length=50, verbose_name='type'),
        ),
    ]
