# Generated by Django 3.1 on 2020-12-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201206_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='phone_number',
            field=models.CharField(max_length=9, verbose_name='phone number'),
        ),
    ]
