# Generated by Django 3.1.2 on 2020-11-01 14:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20201101_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 14, 5, 53, 750741, tzinfo=utc), verbose_name='Date'),
        ),
    ]
