# Generated by Django 3.1 on 2020-11-06 08:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20201101_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 8, 22, 21, 921245, tzinfo=utc), verbose_name='Date'),
        ),
    ]
