# Generated by Django 3.1 on 2020-11-06 09:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20201106_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 9, 33, 5, 871298, tzinfo=utc), verbose_name='Date'),
        ),
    ]
