# Generated by Django 3.1 on 2020-11-06 14:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20201106_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 14, 54, 6, 985287, tzinfo=utc), verbose_name='Date'),
        ),
    ]
