# Generated by Django 3.1 on 2020-12-05 13:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20201106_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 5, 13, 14, 16, 964100, tzinfo=utc), verbose_name='Date'),
        ),
    ]
