# Generated by Django 3.1 on 2020-12-06 10:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20201205_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 6, 10, 55, 35, 863677, tzinfo=utc), verbose_name='Date'),
        ),
    ]
