# Generated by Django 3.1 on 2020-12-06 11:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20201206_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 6, 11, 21, 38, 534770, tzinfo=utc), verbose_name='Date'),
        ),
    ]
